### ISSUE TITLE
Training Time 

### ISSUE THREAD

**Issue by nitish116** [goldkim92/StarGAN-tensorflow#5]
I am running on k80 , aws p2.xlarge , can u tell me how much time does it take for out of the box training 

python main.py --phase=train --image_size=64 --batch_size=16, right after the download?

**Comment by goldkim92** [comment]
I have no idea when training by aws p2.xlarge, but in my case I used 1 Tesla Xp and it took about a day. But The other guy tells me that my code is a little bit wrong, so I should revise it first.
